let __time = 0
const __FPS = 60
let __interval = 1000 / __FPS
let __mainViewport = document.createElement("canvas")
let __mainContext = __mainViewport.getContext("2d")
let __container = document.getElementById("container")
let __keyStatus = {}
let __images = {}
let __sheets = {}
let __animations = {}
let __sounds = {}
const __gameWidth = 1000
const __gameHeight = 700
const __gameScale = 1
let __scenes = {}
let __activeScene = undefined
const AudioContext = window.AudioContext || window.webkitAudioContext;
const audioContext = new AudioContext();
let __currentSong = undefined
let __songQueued = undefined